- name: Deploy Docker container using Ansible
  hosts: webservers
  become: yes

  tasks:
    - name: Pull latest Docker image
      command: docker pull varungucpc007/automated-docker-deployment-cicd:latest

    - name: Stop old container
      command: docker stop docker-cicd-app
      ignore_errors: yes

    - name: Remove old container
      command: docker rm docker-cicd-app
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name docker-cicd-app -p 80:5000 varungucpc007/automated-docker-deployment-cicd:latest
