[webservers]
server1 ansible_host=3.110.91.201 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'
server2 ansible_host=15.206.207.63 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'

