pipeline {
    agent any

    environment {
        IMAGE_NAME = "varungucpc007/automated-docker-deployment-jenkins-ansible"
    }

    stages {

        stage('Clone Code') {
            steps {
                checkout scm
            }
        }

        stage('Check Files') {
            steps {
                sh 'ls -la'
                sh 'ls -la automated-docker-deployment-jenkins-ansible'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('automated-docker-deployment-jenkins-ansible') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Login To Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

stage('Check Ansible') {
    steps {
        sh 'which ansible-playbook'
        sh 'ansible-playbook --version'
    }
}

        
        stage('Deploy Using Ansible') {
            steps {
                dir('automated-docker-deployment-jenkins-ansible') {
                    sh 'ansible-playbook -i inventory.ini deploy.yml'
                }
            }
        }
    }
}
